openapi: 3.0.1
info:
  title: 出行助手
  description: 接入天气和出行信息，结合大模型完成更精确的出行分析。
  version: 'v0.0.1'
servers:
  - url: http://127.0.0.1:9000
paths:
  /weather/info:
    get:
      operationId: weatherInfo
      summary: 获取天气信息
      parameters:
        - in: query
          name: city
          required: true
          schema:
            type: string
          description: 城市名字或地址
        - in: query
          name: extensions
          schema:
            type: string
          description: 气象类型，为base返回实况天气，为all返回预报天气
      responses:
        '200':
          description: 获取天气信息成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/weatherInfo'

components:
  schemas:
    weatherInfo:
      type: object
      required: [city]
      properties:
        city:
          type: string
        extensions:
          type: string
